<?php
namespace Learn3\Film\Model\ResourceModel\Film;
/**
 * Class Collection
 * @package Learn3\Film\Model\ResourceModel\Film
 */
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection {

    /**
     * @var string
     */
    protected $_idFieldName='film_id';

    /**
     *
     */
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('Learn3\Film\Model\Film', 'Learn3\Film\Model\ResourceModel\Film');
    }
    protected function _initSelect()
    {
        parent::_initSelect();
        $this->getSelect()->join(
            ['zero_training_four_film' => $this->getTable('zero_training_four_film_category')], //2nd table name by which you want to join mail table
            'main_table.film_id =zero_training_four_film.film_id',
            []
        )->join(
            [$this->getTable('zero_training_four_film_actor')],
            'main_table.film_id =zero_training_four_film_actor.film_id',
            []
        )->join(
            [$this->getTable('zero_training_four_category')],
            'zero_training_four_film.category_id =zero_training_four_category.category_id',
            ['zero_training_four_category.name']
        )->join(
            [$this->getTable('zero_training_four_actor')],
            'zero_training_four_film_actor.actor_id =zero_training_four_actor.actor_id',
            ['name_actor'=>new \Zend_Db_Expr("CONCAT(zero_training_four_actor.first_name,' ',zero_training_four_actor.last_name)"),'num_actor'=>new \Zend_Db_Expr("COUNT(zero_training_four_film_actor.actor_id)")]
        )->group('zero_training_four_film.film_id')->having('num_actor > ?',5);
    }

}
?>