<?php
namespace Learn8\Student\Model\ResourceModel\Student;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection{

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('Learn8\Student\Model\Student', 'Learn8\Student\Model\ResourceModel\Student');
    }
}

?>