<div id="training" class="test-ui" data-bind="scope:'page'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
{
"#training": {
   "Magento_Ui/js/core/app": {
          "components" : {
             "page": {
                  "component": "Learn9_Module/js/page",
                   "displayArea": "test"
              }
          }
       }
   }
}
</script>
</div>