<?php
namespace Learn3\Film\Model\ResourceModel\Category;
/**
 * Class Collection
 * @package Learn3\Film\Model\ResourceModel\Category
 */

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName='category_id';

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('Learn3\Film\Model\Category', 'Learn3\Film\Model\ResourceModel\Category');
    }
    protected function _initSelect()
    {
        parent::_initSelect();
        $this->getSelect()->join(
            ['zero_training_four_category' => $this->getTable('zero_training_four_film_category')], //2nd table name by which you want to join mail table
            'main_table.category_id =zero_training_four_category.category_id',
            []
        )->join(
            [$this->getTable('zero_training_four_film')],
            'zero_training_four_category.film_id =zero_training_four_film.film_id',
            []
        )->join(
            [$this->getTable('zero_training_four_film_actor')],
            'zero_training_four_film.film_id =zero_training_four_film_actor.film_id',
            []
        )->joinLeft(
            [$this->getTable('zero_training_four_actor')],
            'zero_training_four_film_actor.actor_id =zero_training_four_actor.actor_id',
            ['num_actor'=>new \Zend_Db_Expr("COUNT(zero_training_four_film_actor.actor_id)")]
        )->group('main_table.category_id')->order('num_actor DESC')->limit(5);
    }
}

?>